language: python
jobs:
  include:
  - stage: pypi release
    python: 3.6
    script: skip
    deploy:
      provider: pypi
      user: chill17
      password:
        secure: fwHM4WqrdQjvJ40tWKUo+7rX5JGg0yJxKTNohflqH5+INRW5w4mPIqpQRaSgfbTD8JDvEan4ZiMPxkQGHT/s1w+f8U2dy3WOqKLbPTW/y6kKN3FKSK4npoqdGqKJCD9tMdEoe0o8VfOOVIeUIoyDks/oTzPB1swXF2MbI074pywwLrw+7yGJsW67p9fbCZS5EC/+MBwNvAYf99Z76CSCQauZsYLT0boebj+PwKNGv4WJq4mL0MWNzInLVw/qI6T4wn8S/35zW1JZUCo5KCL2DGxqDpzX4qXVzKL8GVoxFiHTX0q0qXleYjspxItsZ1oZna6VIdU3kgnIRyxojPkvVY+xyWoBsTSHMaOcNq0jh1nwsv035fuOjnzdC+YKQXqEVgvKjzzlwtpIHFnIUjXCU1plUW1KMjFzk+6HdlI70wPIiR8bUZchmxDYZIz+s77bmUQ6hkmXsbSgxeyC8f/nMi4fkmuQhpWX+wIZlU+kfQotmvuS82HEn2PDBmujVa65BA78iVSyu+O/0HBq3ZpRGB0BQObOaEGZu5zCdsH8U/tas7zyIhx02iGI1K0xlkRDHUz4w6SoOlWND+udglz3qpfIKZehSPXAsR4oxViy6ZdwO6TxuMTgTwsj3lN+PAs0tKmENj+gM88ocHY+u0pTaCR2GaE82YZp2rXh/PO5JCY=
      on:
        tags: true
        distributions: sdist bdist_wheel
        repo: pybrarian/check_ezproxy